import type { Desafio } from "./tipos";

export const DESAFIOS_INICIAIS: Desafio[] = [
  {
    id: "forca-e-constancia",
    nome: "Força e Constância",
    chamada: "Treine 20 dias este mês e prove que constância vence intensidade.",
    descricao:
      "O desafio principal do mês. A meta é simples e dura: 20 treinos registrados dentro do período. Cada treino enviado com foto soma pontos, alimenta o ranking e libera os benefícios dos patrocinadores.",
    situacao: "ativo",
    inicio: "2026-07-07",
    fim: "2026-08-05",
    metaTreinos: 20,
    pontosPorTreino: 150,
    participantes: 312,
    premiacaoTotal: 8000,
    premios: [
      { colocacao: "1º lugar", descricao: "R$ 3.000 em produtos + kit completo NutriForce" },
      { colocacao: "2º lugar", descricao: "R$ 2.000 em produtos + camiseta oficial" },
      { colocacao: "3º lugar", descricao: "R$ 1.000 em produtos" },
      { colocacao: "4º ao 10º", descricao: "Cupom exclusivo de 30% nas marcas parceiras" },
    ],
    regras: [
      "Registrar no mínimo 20 treinos dentro do período do desafio.",
      "Cada treino precisa de foto ou vídeo enviado no mesmo dia da atividade.",
      "Duração mínima de 30 minutos por treino registrado.",
      "Somente um treino contabilizado por dia.",
      "Treinos com foto repetida ou fora do período são desclassificados.",
      "Marcar os patrocinadores ao compartilhar rende pontos extras de engajamento.",
    ],
    patrocinadoresIds: ["nutriforce", "energy-lab", "move-performance", "ironfit"],
    banner: "from-lima-400/25 via-grafite-850 to-damatech-500/25",
    imagem: "/fotos/desafio-forca.jpg",
  },
  {
    id: "desafio-21-dias",
    nome: "Desafio 21 Dias",
    chamada: "Vinte e um dias seguidos para transformar treino em hábito.",
    descricao:
      "Formato curto e intenso: 21 dias consecutivos de atividade registrada. Perdeu um dia, a sequência reinicia. Feito para quem quer criar rotina antes de entrar em um desafio longo.",
    situacao: "futuro",
    inicio: "2026-08-10",
    fim: "2026-08-31",
    metaTreinos: 21,
    pontosPorTreino: 120,
    participantes: 96,
    premiacaoTotal: 4500,
    premios: [
      { colocacao: "1º lugar", descricao: "Mensalidade anual em academia parceira" },
      { colocacao: "2º e 3º", descricao: "Kit suplementação Core Nutrition" },
      { colocacao: "Todos que concluírem", descricao: "Selo Hábito 21 no perfil" },
    ],
    regras: [
      "Atividade registrada em 21 dias consecutivos.",
      "Mobilidade e caminhada contam como treino leve nos dias de recuperação.",
      "A sequência reinicia caso um dia fique sem registro.",
      "Duração mínima de 20 minutos por atividade.",
    ],
    patrocinadoresIds: ["core-nutrition", "peak-sports"],
    banner: "from-damatech-500/30 via-grafite-850 to-grafite-850",
    imagem: "/fotos/desafio-21dias.jpg",
  },
  {
    id: "verao-em-movimento",
    nome: "Verão em Movimento",
    chamada: "A campanha de maior premiação do ano, com marcas parceiras juntas.",
    descricao:
      "Desafio sazonal com meta de 24 treinos e trilha de atividades ao ar livre. Reúne todos os patrocinadores da base em uma campanha só, com premiação ampliada e ativações presenciais.",
    situacao: "futuro",
    inicio: "2026-09-01",
    fim: "2026-09-30",
    metaTreinos: 24,
    pontosPorTreino: 150,
    participantes: 148,
    premiacaoTotal: 15000,
    premios: [
      { colocacao: "1º lugar", descricao: "R$ 6.000 em prêmios + ensaio fotográfico esportivo" },
      { colocacao: "2º lugar", descricao: "R$ 4.000 em prêmios" },
      { colocacao: "3º lugar", descricao: "R$ 2.500 em prêmios" },
      { colocacao: "Sorteio entre concluintes", descricao: "R$ 2.500 distribuídos em cupons" },
    ],
    regras: [
      "Registrar no mínimo 24 treinos dentro do mês da campanha.",
      "Pelo menos 6 treinos ao ar livre para concorrer à premiação principal.",
      "Compartilhamento marcando os patrocinadores vale pontuação extra.",
      "Participação aberta a novos inscritos até o quinto dia do período.",
    ],
    patrocinadoresIds: [
      "nutriforce",
      "energy-lab",
      "move-performance",
      "ironfit",
      "core-nutrition",
      "peak-sports",
    ],
    banner: "from-lima-400/25 via-grafite-850 to-sky-500/25",
    imagem: "/fotos/desafio-verao.jpg",
  },
  {
    id: "evolucao-sem-desculpas",
    nome: "Evolução Sem Desculpas",
    chamada: "O desafio que abriu a operação e validou o formato mensal.",
    descricao:
      "Primeira campanha realizada, com meta de 18 treinos em junho. Serviu para calibrar as regras de pontuação, o fluxo de envio de foto e o interesse dos patrocinadores.",
    situacao: "encerrado",
    inicio: "2026-06-01",
    fim: "2026-06-30",
    metaTreinos: 18,
    pontosPorTreino: 150,
    participantes: 274,
    premiacaoTotal: 5000,
    premios: [
      { colocacao: "1º lugar", descricao: "R$ 2.500 em produtos IronFit" },
      { colocacao: "2º lugar", descricao: "R$ 1.500 em produtos" },
      { colocacao: "3º lugar", descricao: "R$ 1.000 em produtos" },
    ],
    regras: [
      "Registrar 18 treinos dentro do mês de junho.",
      "Foto obrigatória em cada registro.",
      "Um treino por dia.",
    ],
    patrocinadoresIds: ["ironfit", "nutriforce"],
    banner: "from-grafite-700 via-grafite-850 to-grafite-850",
    imagem: "/fotos/desafio-evolucao.jpg",
  },
];

export const ID_DESAFIO_ATUAL = "forca-e-constancia";
