import type { Participante } from "./tipos";

/**
 * Participantes fictícios da demonstração. Nenhum nome corresponde a pessoa real.
 * O usuário da demo é o Reginaldo, para o cliente se ver dentro do produto.
 */
export const PARTICIPANTES_INICIAIS: Participante[] = [
  {
    id: "p-bruno",
    nome: "Bruno Silveira",
    apelido: "bruno.silveira",
    ehUsuario: false,
    status: "ativo",
    nivel: 14,
    patente: "Atleta consistente",
    pontos: 2480,
    treinos: 16,
    sequencia: 12,
    desafioId: "forca-e-constancia",
    entrouEm: "2026-06-02",
    cidade: "Juiz de Fora, MG",
    posicaoAnterior: 1,
    gradiente: "from-damatech-500 to-damatech-700",
  },
  {
    id: "p-reginaldo",
    nome: "Reginaldo Moura",
    apelido: "reginaldo.moura",
    ehUsuario: true,
    status: "ativo",
    nivel: 12,
    patente: "Constância em alta",
    pontos: 2150,
    treinos: 13,
    sequencia: 7,
    desafioId: "forca-e-constancia",
    entrouEm: "2026-06-05",
    cidade: "Juiz de Fora, MG",
    posicaoAnterior: 3,
    gradiente: "from-lima-400 to-lima-600",
  },
  {
    id: "p-lucas",
    nome: "Lucas Mendes",
    apelido: "lucas.mendes",
    ehUsuario: false,
    status: "ativo",
    nivel: 11,
    patente: "Ritmo firme",
    pontos: 1980,
    treinos: 13,
    sequencia: 5,
    desafioId: "forca-e-constancia",
    entrouEm: "2026-06-02",
    cidade: "Belo Horizonte, MG",
    posicaoAnterior: 2,
    gradiente: "from-sky-500 to-indigo-600",
  },
  {
    id: "p-rafael",
    nome: "Rafael Antunes",
    apelido: "rafael.antunes",
    ehUsuario: false,
    status: "ativo",
    nivel: 10,
    patente: "Ritmo firme",
    pontos: 1760,
    treinos: 11,
    sequencia: 3,
    desafioId: "forca-e-constancia",
    entrouEm: "2026-06-08",
    cidade: "São Paulo, SP",
    posicaoAnterior: 4,
    gradiente: "from-orange-500 to-rose-600",
  },
  {
    id: "p-gabriela",
    nome: "Gabriela Prado",
    apelido: "gabriela.prado",
    ehUsuario: false,
    status: "ativo",
    nivel: 10,
    patente: "Ritmo firme",
    pontos: 1640,
    treinos: 11,
    sequencia: 6,
    desafioId: "forca-e-constancia",
    entrouEm: "2026-06-09",
    cidade: "Vitória, ES",
    posicaoAnterior: 6,
    gradiente: "from-fuchsia-500 to-purple-600",
  },
  {
    id: "p-marina",
    nome: "Marina Duarte",
    apelido: "marina.duarte",
    ehUsuario: false,
    status: "ativo",
    nivel: 9,
    patente: "Em evolução",
    pontos: 1520,
    treinos: 10,
    sequencia: 4,
    desafioId: "forca-e-constancia",
    entrouEm: "2026-06-11",
    cidade: "Curitiba, PR",
    posicaoAnterior: 5,
    gradiente: "from-teal-400 to-emerald-600",
  },
  {
    id: "p-thiago",
    nome: "Thiago Ramalho",
    apelido: "thiago.ramalho",
    ehUsuario: false,
    status: "ativo",
    nivel: 8,
    patente: "Em evolução",
    pontos: 1380,
    treinos: 9,
    sequencia: 2,
    desafioId: "forca-e-constancia",
    entrouEm: "2026-06-14",
    cidade: "Juiz de Fora, MG",
    posicaoAnterior: 7,
    gradiente: "from-amber-400 to-orange-600",
  },
  {
    id: "p-camila",
    nome: "Camila Bastos",
    apelido: "camila.bastos",
    ehUsuario: false,
    status: "ativo",
    nivel: 7,
    patente: "Em evolução",
    pontos: 1240,
    treinos: 8,
    sequencia: 3,
    desafioId: "forca-e-constancia",
    entrouEm: "2026-06-16",
    cidade: "Niterói, RJ",
    posicaoAnterior: 9,
    gradiente: "from-cyan-400 to-blue-600",
  },
  {
    id: "p-andre",
    nome: "André Nogueira",
    apelido: "andre.nogueira",
    ehUsuario: false,
    status: "ativo",
    nivel: 6,
    patente: "Aquecendo",
    pontos: 1100,
    treinos: 7,
    sequencia: 1,
    desafioId: "forca-e-constancia",
    entrouEm: "2026-06-18",
    cidade: "Uberlândia, MG",
    posicaoAnterior: 8,
    gradiente: "from-violet-500 to-indigo-700",
  },
  {
    id: "p-fernanda",
    nome: "Fernanda Aguiar",
    apelido: "fernanda.aguiar",
    ehUsuario: false,
    status: "ativo",
    nivel: 6,
    patente: "Aquecendo",
    pontos: 980,
    treinos: 7,
    sequencia: 2,
    desafioId: "forca-e-constancia",
    entrouEm: "2026-06-21",
    cidade: "Recife, PE",
    posicaoAnterior: 10,
    gradiente: "from-pink-500 to-rose-700",
  },
  {
    id: "p-diego",
    nome: "Diego Vasques",
    apelido: "diego.vasques",
    ehUsuario: false,
    status: "pendente",
    nivel: 4,
    patente: "Aquecendo",
    pontos: 820,
    treinos: 6,
    sequencia: 0,
    desafioId: "forca-e-constancia",
    entrouEm: "2026-07-14",
    cidade: "Santos, SP",
    posicaoAnterior: 11,
    gradiente: "from-lime-500 to-green-700",
  },
  {
    id: "p-patricia",
    nome: "Patrícia Rangel",
    apelido: "patricia.rangel",
    ehUsuario: false,
    status: "bloqueado",
    nivel: 3,
    patente: "Aquecendo",
    pontos: 640,
    treinos: 4,
    sequencia: 1,
    desafioId: "forca-e-constancia",
    entrouEm: "2026-07-02",
    cidade: "Goiânia, GO",
    posicaoAnterior: 12,
    gradiente: "from-slate-400 to-slate-600",
  },
];

export const ID_USUARIO = "p-reginaldo";
