import type { Patrocinador } from "./tipos";

/** Marcas fictícias, criadas apenas para a demonstração. */
export const PATROCINADORES_INICIAIS: Patrocinador[] = [
  {
    id: "nutriforce",
    nome: "NutriForce",
    segmento: "Suplementação",
    descricao:
      "Linha de suplementos voltada para quem treina com regularidade e acompanha resultado de perto.",
    beneficio: "15% de desconto em toda a linha proteica para participantes ativos do desafio.",
    cupom: "HUBFIT15",
    desconto: "15% OFF",
    desafiosIds: ["forca-e-constancia", "verao-em-movimento", "evolucao-sem-desculpas"],
    ativo: true,
    cor: "#c6f24e",
    monograma: "NF",
    foto: "/fotos/detalhe-pesos.jpg",
  },
  {
    id: "energy-lab",
    nome: "Energy Lab",
    segmento: "Pré-treino e hidratação",
    descricao:
      "Bebidas funcionais e pré-treino desenvolvidos para sessões longas e treinos ao ar livre.",
    beneficio: "Kit hidratação com 20% de desconto para quem concluir a meta mensal.",
    cupom: "ENERGY20",
    desconto: "20% OFF",
    desafiosIds: ["forca-e-constancia", "verao-em-movimento"],
    ativo: true,
    cor: "#4a8cf7",
    monograma: "EL",
    foto: "/fotos/tipo-corrida.jpg",
  },
  {
    id: "move-performance",
    nome: "Move Performance",
    segmento: "Vestuário esportivo",
    descricao: "Roupa técnica para treino de força, corrida e atividades funcionais.",
    beneficio: "10% de desconto e frete grátis acima de R$ 199 para participantes.",
    cupom: "MOVE10",
    desconto: "10% OFF",
    desafiosIds: ["forca-e-constancia", "verao-em-movimento"],
    ativo: true,
    cor: "#f6c445",
    monograma: "MP",
    foto: "/fotos/atleta-funcional.jpg",
  },
  {
    id: "ironfit",
    nome: "IronFit",
    segmento: "Equipamentos",
    descricao: "Equipamentos e acessórios de treino para academia e para montar estrutura em casa.",
    beneficio: "Cupom de R$ 120 em acessórios para os dez primeiros do ranking.",
    cupom: "IRON120",
    desconto: "R$ 120",
    desafiosIds: ["forca-e-constancia", "verao-em-movimento", "evolucao-sem-desculpas"],
    ativo: true,
    cor: "#b3bcc9",
    monograma: "IF",
    foto: "/fotos/ambiente-academia.jpg",
  },
  {
    id: "core-nutrition",
    nome: "Core Nutrition",
    segmento: "Nutrição e alimentação",
    descricao: "Refeições prontas e acompanhamento nutricional para rotina de treino.",
    beneficio: "Primeira avaliação nutricional sem custo para quem concluir um desafio.",
    cupom: "COREZERO",
    desconto: "Avaliação grátis",
    desafiosIds: ["desafio-21-dias", "verao-em-movimento"],
    ativo: true,
    cor: "#3ecf8e",
    monograma: "CN",
    foto: "/fotos/tipo-mobilidade.jpg",
  },
  {
    id: "peak-sports",
    nome: "Peak Sports",
    segmento: "Calçados e corrida",
    descricao: "Tênis de performance e acessórios para corrida de rua e trilha.",
    beneficio: "25% de desconto na linha de corrida durante a campanha patrocinada.",
    cupom: "PEAK25",
    desconto: "25% OFF",
    desafiosIds: ["desafio-21-dias", "verao-em-movimento"],
    ativo: false,
    cor: "#f2545b",
    monograma: "PS",
    foto: "/fotos/atleta-corrida.jpg",
  },
];
